### ISSUE TITLE
litecoin?

### ISSUE THREAD

**Issue by Ollemesh** [ruimarinho/bitcoin-core#32]
Hello,
Thank You for this useful module!

A simple question: Can I use it for working with litecoin wallet, which have a similar rpc api? 
And if I can, how I should configure this?

**Comment by pedrobranco** [comment]
Hello there,

You can point the `bitcoin-core` client to your `litecoind` (litecoin ip / port).

```js
const Client = require('bitcoin-core');
const client = new Client({ 
  host: '<your litecoind ip>', 
  password: '<your rpc username password>',
  port: <your litecoind port>, 
  username: '<your rpc username>'
});
```

Care to check if the RPC methods that you need in `litecoind` are available in [here](https://github.com/ruimarinho/bitcoin-core/blob/master/src/methods.js).

Cheers.

**Comment by Ollemesh** [comment]
Hello, 
Thanks for your answer, but I still have a trouble:
![Error screen shot](https://user-images.githubusercontent.com/6448390/30267671-f7a43216-96eb-11e7-8ae1-6ab4a78fe684.png)

My litecoin.conf: 
```
server=1
daemon=1
gen=0
testnet=1
rpcallowip=127.0.0.1
rpcallowip=192.168.42.82
rpcuser=user
rpcpassword=password
```
(Bitcoin core works fine having the same settings in the same mashine)

My JS file: 
```javascript
const client = new Client({
    host: '192.168.128.20',
    port: '19335',
    username: 'user',
    password: 'password'
})

client.getInfo()
    .then(info => console.log(info))
    .catch(error => console.log(error))
```
19335 is being listened: 
![netstat](https://user-images.githubusercontent.com/6448390/30268163-88d89758-96ed-11e7-9d79-7ada9a6ff90d.png)

litecoind is alive: 
![litecoin-cli getinfo](https://user-images.githubusercontent.com/6448390/30268287-f2a6112e-96ed-11e7-93f7-179d33b760f5.png)

RPS method, which i used is `getInfo()`.

I must apologize for troubling you, 
thank You for the module, 
and if You need I can try to help You with it (if my scale is enough)
--

**Comment by Ollemesh** [comment]
stable litecoind version did not help

**Comment by Ollemesh** [comment]
Done!
I start to read all listening ports list and find some another port 19332/litecoin
I tried to set it in options and everything have started to work.

![2017-09-11 16 17 29](https://user-images.githubusercontent.com/6448390/30276289-06cc1dbe-970d-11e7-9c86-b6f9104208a4.png)
