### ISSUE TITLE
getBlockchainInfo verificationprogress rounding issue

### ISSUE THREAD

**Issue by shkschneider** [ruimarinho/bitcoin-core#35]
bitcoin-cli returns me "verificationprogress": 1
but bitcoin-core returns me 0.9999941262782213

Since this is the return of the library I have no way to fix that rounding issue.
I would expect 1 to be returned.
(I know this is a common javascript problem.)
Generally speaking, I would expect this library to delive 8 decimals number (8 decimals for satoshis). Maybe return numbers as strings and let the client interpret it like he wants it to (many libraries available).

**Comment by ruimarinho** [comment]
Indeed. Thanks for reporting this issue.

**Comment by pedrobranco** [comment]
Will submit a PR for this. Thanks for reporting this issue @shkschneider.

**Comment by shkschneider** [comment]
Looks like you already worked a bit on it: https://github.com/pedrobranco/bitcoin-core/commit/9ca5cafd28b02232e0154763530917a5e88409a5
I'm looking forward to see that issue solved :)

**Comment by ruimarinho** [comment]
Fixed in https://github.com/ruimarinho/bitcoin-core/commit/c035b34aefa65164857f521a75f356e65448b9e6. Thanks!
