### ISSUE TITLE
Enabling named parameters

### ISSUE THREAD

**Issue by toriaezunama** [ruimarinho/bitcoin-core#52]
Please update the documentation to say that in order for named parameters to be *enabled* you must specify the version in the options passed at initialisation.

`hasNamedParametersSupport` is `false` by default and only set to true if both `version` is set *and* `semver.satisfies(version, '>=0.14.0')`

**Comment by ruimarinho** [comment]
You are very right. Would you like to submit a PR with that additional information?

**Comment by toriaezunama** [comment]
Done. #56

**Comment by ruimarinho** [comment]
Closed by https://github.com/ruimarinho/bitcoin-core/pull/56.
