### ISSUE TITLE
Document the completeness and roadmap of this module

### ISSUE THREAD

**Issue by fresheneesz** [ruimarinho/bitcoin-core#54]
Is this module complete? It seems to be missing a ton of necessary methods. Could someone please document more clearly what is planned on being added? 

This module needs way better documentation in general. Stuff like "returns information about a block" isn't really enough. This needs a description of the exact result format, or at least a link to somewhere the does document that.

**Comment by ruimarinho** [comment]
It depends on your definition of complete. In open source, projects are always evolving and so complete can be a rather strong word. What are you looking for specifically? What methods would you like to see that are not present?

> This module needs way better documentation in general. Stuff like "returns information about a block" isn't really enough. This needs a description of the exact result format, or at least a link to somewhere the does document that.

Would you like to contribute by opening PRs with those descriptions?

**Comment by fresheneesz** [comment]
Well I guess I started using the `command` method, which I didn't realize existed. That kind of fulfills all my needs. Even tho the `command` method is mentioned in passing in a few examples on the readme, its not actually documented. I'll just add that in my readme edit.
