### ISSUE TITLE
rest/blockhash?

### ISSUE THREAD

**Issue by mahalamobile** [ruimarinho/bitcoin-core#67]
https://diff.cryptothis.com/rest/blockhash/520128.json

Hi am trying to be able to run this on my server via nodejs, however i see your package doesnt have the blockhash option, was this depreciated? any ideas on how to make use of this?

thanks
neil

**Comment by ruimarinho** [comment]
You probably mean https://github.com/ruimarinho/bitcoin-core/blob/master/src/index.js#L169 right?
