### ISSUE TITLE
sendMany command is not processing transaction

### ISSUE THREAD

**Issue by ghost** [ruimarinho/bitcoin-core#74]
I tried the following command
client.sendMany('test1', { mjSk1Ny9spzU2fouzYgLqGUD8U41iR35QN: 0.1, mgnucj8nYqdrPFh2JfZSB1NmUThUGnmsqe: 0.2 }, 6, 'Example Transaction');

No transaction is initiated
How can I see log for this command?

**Comment by pedrobranco** [comment]
You can see `bitcoin-core` logs by defining the environment variable as `DEBUG=bitcoin-core` and see if it helps. 

You can use `bunyan` to parse those logs:
```shell
DEBUG=bitcoin-core node your_script.js | bunyan
```
