### ISSUE TITLE
RPC changes on bitcoin core v0.17.0

### ISSUE THREAD

**Issue by jeromevonk** [ruimarinho/bitcoin-core#77]
There are new RPC methods on [bitcoin core version 0.17.0](https://bitcoincore.org/en/releases/0.17.0/).

Will there be support for this new methods?

**Comment by pedrobranco** [comment]
> Will there be support for this new methods?

Yes, but if you give us a help you can contribute by submitting a PR for adding support or listing here all the RPC changes 💯

**Comment by jeromevonk** [comment]
From 0.16.0:
rescanblockchain
savemempool

From 0.17.0
converttopsbt
createpsbt
walletcreatefundedpsbt
walletprocesspsbt
finalizepsbt
combinepsbt
decodepsbt
signrawtransactionwithkey
signrawtransactionwithwallet
getaddressinfo
getaddressesbylabel
getreceivedbylabel
listlabels
listreceivedbylabel
setlabel

List of all RPCs on v0.17.0 attached
[RPC Calls 0.17.0.txt](https://github.com/ruimarinho/bitcoin-core/files/2520525/RPC.Calls.0.17.0.txt)

**Comment by juscamarena** [comment]
I can add a PR with most of these.

**Comment by juscamarena** [comment]
Adding these new methods is actually the easiest part.

Doing it the right way is hard as upgrading the docker image to bitcoind 0.17 breaks a lot of tests, this will probably need a major version upgrade.

Should I up the default docker image to use 0.17 and update all the tests targeting this or should I create a new bitcoind 0.17 image and create a separate set of tests for this? @ruimarinho @pedrobranco I'm happy to spend the time doing so as I use this package a lot.

**Comment by juscamarena** [comment]
I've created a PR that still needs some work here #84

**Comment by pedrobranco** [comment]
Fixed by #94.
