### ISSUE TITLE
Unhandled rejection Error: no auth mechanism defined

### ISSUE THREAD

**Issue by aryeharmon** [ruimarinho/bitcoin-core#81]
unable to make any requests, getting error: Unhandled rejection Error: no auth mechanism defined

**Comment by pedrobranco** [comment]
Please confirm that you have defined a `rpcusername` and `rpcpassword` on the `bitcoind`, and also 
pass that as `username` and `password` in the bitcoin-core client.

Example available [here](https://github.com/ruimarinho/bitcoin-core/blame/master/README.md#L163).

**Comment by isghe** [comment]
it's `rpcuser`, not `rpcusername`

**Comment by pedrobranco** [comment]
> it's rpcuser, not rpcusername

True, my mistake 👍  

@aryeharmon did you solved it?

I'm closing this since it seems related to `bitcoind` configuration.
