### ISSUE TITLE
RPC changes on Bitcoin v0.18.0

### ISSUE THREAD

**Issue by justinmeiners** [ruimarinho/bitcoin-core#90]
Related to #77.

https://bitcoincore.org/en/releases/0.18.0/

Of particular importance for me is the removal of `signrawtransaction`

> signrawtransaction is removed after being deprecated and hidden behind a special configuration option in version 0.17.0.

This is now replaced with: `signrawtransactionwithkey`

**Comment by jeamick** [comment]
https://github.com/ruimarinho/bitcoin-core/pull/80

**Comment by pedrobranco** [comment]
@justinmeiners In the next few days a minor release will come out with this new method.

**Comment by pedrobranco** [comment]
Already available in version `2.2.0`.
