### ISSUE TITLE
How to communicate with encrypted wallet

### ISSUE THREAD

**Issue by parasjain** [ruimarinho/bitcoin-core#92]
I am running a full node in my local system, however I have encrypted my wallet.dat file with a passphrase. What changes do I need to make to be able to communicate with the encrypted wallet?

**Comment by pedrobranco** [comment]
Please kindly check the `walletpassphrase` documentation [here](https://bitcoincore.org/en/doc/0.17.0/rpc/wallet/walletpassphrase/).

**Comment by pedrobranco** [comment]
Closing this issue since is not related with this project.
