### ISSUE TITLE
Add createWallet method

### ISSUE THREAD

**Issue by tiero** [ruimarinho/bitcoin-core#93]
It seems is not exported yet. There is a way to do a raw rpc call with this library, like in this case?

**Comment by pedrobranco** [comment]
You can use `client.command` method to call RPC methods. Example:
```js
client.command('createwallet', 'foobar', true)
  .then(response => console.log(response));
// Outputs: { name: 'foobar', warning: '' }
```

**Comment by pedrobranco** [comment]
Now you can use directly the method `createWallet` on the latest version `v2.2.0`.
